language: c
compiler:
  - gcc-4.7
  - gcc-4.9
  - gcc-5
  - gcc-6
  - clang-3.6
  - clang-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.8
    packages:
      - gcc-4.7
      - gcc-4.9
      - gcc-5
      - gcc-6
      - clang-3.6
      - clang-3.8

script:
  - $CC -march=native -v -Q --help=target
  - $CC -march=core-avx-i -v -Q --help=target
  - $CC -march=broadwell -v -Q --help=target
  - make
